apiVersion: v1
kind: Service
metadata:
  name: {{ include "nvidia-blueprint-rag.fullname" . }}
  labels:
    {{- include "nvidia-blueprint-rag.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "nvidia-blueprint-rag.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rag-server
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
