{{- if .Values.ngcApiSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ngcApiSecret.name | default "ngc-api" }}
type: Opaque
stringData:
  NGC_API_KEY: {{ .Values.ngcApiSecret.password | quote }}
  NGC_CLI_API_KEY: {{ .Values.ngcApiSecret.password | quote }}
  NVIDIA_API_KEY: {{ .Values.ngcApiSecret.password | quote }}
{{- end }}
{{- if .Values.imagePullSecret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name | default "ngc-secret" }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {"auths":{"{{ .Values.imagePullSecret.registry }}":{"username":{{ .Values.imagePullSecret.username | quote }},"password":{{ .Values.imagePullSecret.password | quote }},"auth":"{{ printf "%s:%s" .Values.imagePullSecret.username .Values.imagePullSecret.password | b64enc }}"}}}
{{- end }}
