{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus data source", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "query_result(up{})" },
   { "name": "instance", "label": "Instance", "query": "query_result(up{})" }
  ]
 },
 "panels": [
  {
   "title": "Avg Total (Input + Output)  words",
   "type": "stat",
   "description": "Avg total (input + output) tokens",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_tokens{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Output Words",
   "type": "stat",
   "description": "Avg output words",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "output_tokens{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Input Words",
   "type": "stat",
   "description": "Avg input words",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "input_tokens{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg words per chunk",
   "type": "stat",
   "description": "Avg words per chunk",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_words_per_chunk{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Usage metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Input tokens per request",
   "type": "timeseries",
   "description": "Input tokens per request",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "input_tokens{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output tokens per request",
   "type": "timeseries",
   "description": "Output tokens per request",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "output_tokens{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total tokens per request",
   "type": "timeseries",
   "description": "Total tokens per request",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "total_tokens{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg words per chunk per request",
   "type": "timeseries",
   "description": "Avg words per chunk per request",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "avg_words_per_chunk{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}