
name: Build and Push on PR

on:
  pull_request:
    types: [synchronize]

jobs:
  build-and-push-rag:
    runs-on: ubuntu-latesta
    env:
      # OCI AUTH
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
      # IMAGE VARS
      RAG_IMAGE_NAME: corrino-devops-repository/nvidia-rag-retrieval-oci
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into OCIR
        uses: oracle-actions/login-ocir@v1.3.0
        id: login-ocir
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}
      
      - name: Compute short SHA
        id: short-sha
        run: echo "value=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build RAG Docker Image
        run: |
          docker build -t "${{ env.RAG_IMAGE_NAME }}":pr-${{ steps.short-sha.outputs.value }} -f ./Dockerfile .

      - name: Tag and Push RAG Docker Image
        env:
          IMAGE_REMOTE: "iad.ocir.io/${{ secrets.OCI_TENANCY_NAMESPACE }}/${{ env.RAG_IMAGE_NAME }}"
        run: |
          docker tag "${{ env.RAG_IMAGE_NAME }}:pr-${{ steps.short-sha.outputs.value }}" "${{ env.IMAGE_REMOTE }}:pr-${{ steps.short-sha.outputs.value }}"
          docker push "${{ env.IMAGE_REMOTE }}:pr-${{ steps.short-sha.outputs.value }}"

  build-and-push-ingestion:
    runs-on: ubuntu-latest
    env:
      # OCI AUTH
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
      # IMAGE VARS
      INGEST_IMAGE_NAME: corrino-devops-repository/nvidia-rag-ingestion-oci
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into OCIR
        uses: oracle-actions/login-ocir@v1.3.0
        id: login-ocir
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}
      
      - name: Compute short SHA
        id: short-sha
        run: echo "value=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build Ingest Docker Image
        run: |
          docker build -t "${{ env.INGEST_IMAGE_NAME }}":pr-${{ steps.short-sha.outputs.value }} -f ./Dockerfile .

      - name: Tag and Push Ingest Docker Image
        env:
          IMAGE_REMOTE: "iad.ocir.io/${{ secrets.OCI_TENANCY_NAMESPACE }}/${{ env.INGEST_IMAGE_NAME }}"
        run: |
          docker tag "${{ env.INGEST_IMAGE_NAME }}:pr-${{ steps.short-sha.outputs.value }}" "${{ env.IMAGE_REMOTE }}:pr-${{ steps.short-sha.outputs.value }}"
          docker push "${{ env.IMAGE_REMOTE }}:pr-${{ steps.short-sha.outputs.value }}"
